version: '3.7'

services:
  neo4j:
    build:
      context: .
      dockerfile: neo4j.Dockerfile
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
    - $HOME/neo4j/logs:/logs

  redisgraph:
    image: redislabs/redisgraph:2.8.13
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    depends_on:
      - neo4j
      - redisgraph
    links:
      - neo4j
      - redisgraph
    ports:
      - "3030:3030"
#
  swagger:
    image: swaggerapi/swagger-ui:v4.12.0
    ports:
      - "8888:8080"
    environment:
      - SWAGGER_JSON=/var/app/swagger/swagger.yaml
    volumes:
    - ./swagger:/var/app/swagger
